import Head from "next/head"
import Header from "./header"
import Footer from "./footer"

export const symposiumTitle = "Southeast Data Librarian Symposium 2022"

const Layout = ({ children }: {children: React.ReactNode}) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
      </Head>
      <Header />
      <main className="container mx-auto max-w-screen-md mt-24 px-3 sm:px-4 text-gray-800">{children}</main>
      <Footer />
    </>
  )
}

export default Layout